# fly.toml app configuration file generated for demo-wild-fog-9305 on 2025-07-02T15:11:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-wild-fog-9305'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
